version: 'installed-packages-diff/3'
groups:
  db:
    type: rpm
    servers:
      - url: ssh://root@dbdev
        excludes:
          - "missing"
      - url: ssh://root@dblive

  web:
    servers:
      - url: ssh://root@webdev
        excludes:
          - "missing"
      - url: ssh://root@weblive
